local load = require("__mklv-modern-art-lib__.load")

load({
	imagepath = "__mklv-modern-art-mangione__/graphics/images/",
	animpath = "__mklv-modern-art-mangione__/graphics/animations/",
	images = {
		{
			ingredients = { { type = "item", name = "stone", amount = 1 } },
			localised_description = "Luigi Mangione enjoying a day at the beach.",
			localised_name = "Mangione at the beach",
			name = "beach",
			scale = 1,
			size = { 312, 982 },
		},
		{
			ingredients = { { type = "item", name = "advanced-circuit", amount = 1 } },
			localised_description = "Portrait of a freedom fighter.",
			localised_name = "Mancheone",
			name = "che",
			scale = 1,
			size = { 291, 398 },
		},
		{
			ingredients = { { type = "item", name = "electronic-circuit", amount = 1 } },
			localised_description = "A classic hero.",
			localised_name = "It's a me!",
			name = "clay",
			scale = 1,
			size = { 900, 1400 },
		},
		{
			ingredients = { { type = "item", name = "holmium-plate", amount = 1 } },
			localised_description = "Always and forever.",
			localised_name = "But daddy!",
			name = "daddy",
			scale = 1,
			size = { 301, 361 },
		},
		{
			ingredients = { { type = "item", name = "railgun-ammo", amount = 1 } },
			localised_description = "Daringly spicy.",
			localised_name = "hot",
			name = "fire",
			scale = 1,
			size = { 907, 1687 },
		},
		{
			ingredients = { { type = "item", name = "supercapacitor", amount = 1 } },
			localised_description = "He's not like the other boys.",
			localised_name = "I can fix him",
			name = "fix-him",
			scale = 1,
			size = { 327, 359 },
		},
		{
			ingredients = { { type = "item", name = "iron-stick", amount = 1 } },
			localised_description = "Deny, Defend, Depose.",
			localised_name = "Free Luigi",
			name = "free-luigi",
			scale = 1,
			size = { 502, 321 },
		},
		{
			ingredients = { { type = "item", name = "iron-gear-wheel", amount = 1 } },
			localised_description = "",
			localised_name = "Free My Man",
			name = "free-my-man",
			scale = 1,
			size = { 172, 200 },
		},
		{
			ingredients = { { type = "item", name = "jelly", amount = 1 } },
			localised_description = "",
			localised_name = "Luigi on a hike",
			name = "hike",
			scale = 1,
			size = { 684, 798 },
		},
		{
			ingredients = { { type = "item", name = "superconductor", amount = 1 } },
			localised_description = "",
			localised_name = "McDonalds Smile",
			name = "mcd",
			scale = 1,
			size = { 261, 393 },
		},
		{
			ingredients = { { type = "item", name = "electronic-circuit", amount = 1 } },
			localised_description = "Just look at him jump!",
			localised_name = "Jump",
			name = "jump",
			scale = 1,
			size = { 900, 1660 },
		},
		{
			ingredients = { { type = "item", name = "ice", amount = 1 } },
			localised_description = "Enjoying a relaxing day out and about.",
			localised_name = "Luigi Mangione at the park",
			name = "park",
			scale = 1,
			size = { 816, 1194 },
		},
		{
			ingredients = { { type = "item", name = "electric-engine-unit", amount = 1 } },
			localised_description = "Like Jesus before the Romans.",
			localised_name = "Perp Walk",
			name = "perp-walk",
			scale = 1,
			size = { 249, 419 },
		},
		{
			ingredients = { { type = "item", name = "plastic-bar", amount = 1 } },
			localised_description = "A true connoisseur of fine culture.",
			localised_name = "Luigi Mangione at the Philadelphia Museum of Art",
			name = "philly",
			scale = 1,
			size = { 225, 351 },
		},
		{
			ingredients = { { type = "item", name = "rocket-fuel", amount = 1 } },
			localised_description = "He wiped the competition.",
			localised_name = "Proletarians' Person of the Year",
			name = "prole",
			scale = 1,
			size = { 500, 704 },
		},
		{
			ingredients = { { type = "item", name = "rocket-fuel", amount = 1 } },
			localised_description = "He wiped the competition.",
			localised_name = "Shootin' shells",
			name = "red-shell",
			scale = 1,
			size = { 900, 900 },
		},
		{
			ingredients = { { type = "item", name = "solid-fuel", amount = 1 } },
			localised_description = "",
			localised_name = "Luigi Mangione wearing a red sweater",
			name = "red-sweater",
			scale = 1,
			size = { 369, 335 },
		},
		{
			ingredients = { { type = "item", name = "uranium-rounds-magazine", amount = 1 } },
			localised_description = "Known for his courage and selflessness.",
			localised_name = "Patron Saint Mangione",
			name = "saint",
			scale = 1,
			size = { 478, 783 },
		},
		{
			ingredients = { { type = "item", name = "advanced-circuit", amount = 1 } },
			localised_description = "Known for his courage and selflessness.",
			localised_name = "Flying Luigi",
			name = "yoshi",
			scale = 1,
			size = { 900, 980 },
		},
	},
	animations = {},
})
