local load = require("__mklv-modern-art-lib__.load")

local jellynut = "wood"
local tree = "wood"
local yumako = "wood"

if mods["space-age"] then
  jellynut = "jellynut-seed"
  tree = "tree-seed"
  yumako = "yumako-seed"
end


load({
  imagepath = "__mklv-modern-art-potted-plants__/graphics/images/",
  animpath = "__mklv-modern-art-potted-plants__/graphics/animations/",
  mod_name = "potted-plants",
  images = {
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 0",
      name = "potted-plant-00",
      scale = 0.3,
      size = { 320, 470 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 1",
      name = "potted-plant-01",
      scale = 0.3,
      size = { 320, 386 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 2",
      name = "potted-plant-02",
      scale = 0.3,
      size = { 320, 397 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 3",
      name = "potted-plant-03",
      scale = 0.3,
      size = { 320, 366 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 4",
      name = "potted-plant-04",
      scale = 0.3,
      size = { 320, 371 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 5",
      name = "potted-plant-05",
      scale = 0.3,
      size = { 320, 417 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 6",
      name = "potted-plant-06",
      scale = 0.3,
      size = { 320, 427 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 7",
      name = "potted-plant-07",
      scale = 0.3,
      size = { 320, 415 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 8",
      name = "potted-plant-08",
      scale = 0.3,
      size = { 320, 552 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 9",
      name = "potted-plant-09",
      scale = 0.3,
      size = { 320, 612 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 10",
      name = "potted-plant-10",
      scale = 0.3,
      size = { 320, 448 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 11",
      name = "potted-plant-11",
      scale = 0.3,
      size = { 320, 387 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 12",
      name = "potted-plant-12",
      scale = 0.3,
      size = { 320, 352 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 13",
      name = "potted-plant-13",
      scale = 0.3,
      size = { 320, 582 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 14",
      name = "potted-plant-14",
      scale = 0.3,
      size = { 320, 328 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 15",
      name = "potted-plant-15",
      scale = 0.3,
      size = { 320, 531 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 16",
      name = "potted-plant-16",
      scale = 0.3,
      size = { 320, 342 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 17",
      name = "potted-plant-17",
      scale = 0.3,
      size = { 320, 346 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 18",
      name = "potted-plant-18",
      scale = 0.3,
      size = { 320, 413 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 19",
      name = "potted-plant-19",
      scale = 0.3,
      size = { 320, 395 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 20",
      name = "potted-plant-20",
      scale = 0.3,
      size = { 320, 318 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 21",
      name = "potted-plant-21",
      scale = 0.3,
      size = { 320, 359 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 22",
      name = "potted-plant-22",
      scale = 0.3,
      size = { 320, 399 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 23",
      name = "potted-plant-23",
      scale = 0.3,
      size = { 320, 374 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 24",
      name = "potted-plant-24",
      scale = 0.3,
      size = { 320, 330 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 25",
      name = "potted-plant-25",
      scale = 0.3,
      size = { 320, 336 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 26",
      name = "potted-plant-26",
      scale = 0.3,
      size = { 320, 344 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 27",
      name = "potted-plant-27",
      scale = 0.3,
      size = { 320, 346 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 28",
      name = "potted-plant-28",
      scale = 0.3,
      size = { 320, 317 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 29",
      name = "potted-plant-29",
      scale = 0.3,
      size = { 320, 336 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 30",
      name = "potted-plant-30",
      scale = 0.3,
      size = { 320, 398 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 31",
      name = "potted-plant-31",
      scale = 0.3,
      size = { 320, 427 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 32",
      name = "potted-plant-32",
      scale = 0.3,
      size = { 320, 403 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 33",
      name = "potted-plant-33",
      scale = 0.3,
      size = { 320, 353 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 34",
      name = "potted-plant-34",
      scale = 0.3,
      size = { 320, 461 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 35",
      name = "potted-plant-35",
      scale = 0.3,
      size = { 320, 347 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 36",
      name = "potted-plant-36",
      scale = 0.3,
      size = { 320, 464 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 37",
      name = "potted-plant-37",
      scale = 0.3,
      size = { 320, 372 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 38",
      name = "potted-plant-38",
      scale = 0.3,
      size = { 320, 458 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 39",
      name = "potted-plant-39",
      scale = 0.3,
      size = { 320, 334 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 40",
      name = "potted-plant-40",
      scale = 0.3,
      size = { 320, 337 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 41",
      name = "potted-plant-41",
      scale = 0.3,
      size = { 320, 426 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 42",
      name = "potted-plant-42",
      scale = 0.3,
      size = { 320, 451 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 43",
      name = "potted-plant-43",
      scale = 0.3,
      size = { 320, 329 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 44",
      name = "potted-plant-44",
      scale = 0.3,
      size = { 320, 364 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 45",
      name = "potted-plant-45",
      scale = 0.3,
      size = { 320, 390 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 46",
      name = "potted-plant-46",
      scale = 0.3,
      size = { 320, 354 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 47",
      name = "potted-plant-47",
      scale = 0.3,
      size = { 320, 397 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 48",
      name = "potted-plant-48",
      scale = 0.3,
      size = { 320, 350 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 49",
      name = "potted-plant-49",
      scale = 0.3,
      size = { 320, 449 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 50",
      name = "potted-plant-50",
      scale = 0.3,
      size = { 320, 358 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 51",
      name = "potted-plant-51",
      scale = 0.3,
      size = { 320, 340 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 52",
      name = "potted-plant-52",
      scale = 0.3,
      size = { 320, 333 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 53",
      name = "potted-plant-53",
      scale = 0.3,
      size = { 320, 449 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 54",
      name = "potted-plant-54",
      scale = 0.3,
      size = { 320, 360 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 55",
      name = "potted-plant-55",
      scale = 0.3,
      size = { 320, 438 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 56",
      name = "potted-plant-56",
      scale = 0.3,
      size = { 320, 477 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 57",
      name = "potted-plant-57",
      scale = 0.3,
      size = { 320, 391 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 58",
      name = "potted-plant-58",
      scale = 0.3,
      size = { 320, 335 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 59",
      name = "potted-plant-59",
      scale = 0.3,
      size = { 320, 415 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 60",
      name = "potted-plant-60",
      scale = 0.3,
      size = { 320, 393 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 61",
      name = "potted-plant-61",
      scale = 0.3,
      size = { 320, 325 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 62",
      name = "potted-plant-62",
      scale = 0.3,
      size = { 320, 383 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 63",
      name = "potted-plant-63",
      scale = 0.3,
      size = { 320, 335 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 64",
      name = "potted-plant-64",
      scale = 0.3,
      size = { 320, 446 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 65",
      name = "potted-plant-65",
      scale = 0.3,
      size = { 320, 825 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 66",
      name = "potted-plant-66",
      scale = 0.3,
      size = { 320, 367 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 67",
      name = "potted-plant-67",
      scale = 0.3,
      size = { 320, 363 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 68",
      name = "potted-plant-68",
      scale = 0.3,
      size = { 320, 350 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 69",
      name = "potted-plant-69",
      scale = 0.3,
      size = { 320, 396 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 70",
      name = "potted-plant-70",
      scale = 0.3,
      size = { 320, 347 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 71",
      name = "potted-plant-71",
      scale = 0.3,
      size = { 320, 372 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 72",
      name = "potted-plant-72",
      scale = 0.3,
      size = { 320, 381 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 73",
      name = "potted-plant-73",
      scale = 0.3,
      size = { 320, 403 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 74",
      name = "potted-plant-74",
      scale = 0.3,
      size = { 320, 436 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 75",
      name = "potted-plant-75",
      scale = 0.3,
      size = { 320, 448 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 76",
      name = "potted-plant-76",
      scale = 0.3,
      size = { 320, 410 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 77",
      name = "potted-plant-77",
      scale = 0.3,
      size = { 320, 453 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 78",
      name = "potted-plant-78",
      scale = 0.3,
      size = { 320, 419 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 79",
      name = "potted-plant-79",
      scale = 0.3,
      size = { 320, 408 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 80",
      name = "potted-plant-80",
      scale = 0.3,
      size = { 320, 376 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 81",
      name = "potted-plant-81",
      scale = 0.3,
      size = { 320, 377 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 82",
      name = "potted-plant-82",
      scale = 0.3,
      size = { 320, 371 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 83",
      name = "potted-plant-83",
      scale = 0.3,
      size = { 320, 415 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 84",
      name = "potted-plant-84",
      scale = 0.3,
      size = { 320, 328 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 85",
      name = "potted-plant-85",
      scale = 0.3,
      size = { 320, 396 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 86",
      name = "potted-plant-86",
      scale = 0.3,
      size = { 320, 401 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 87",
      name = "potted-plant-87",
      scale = 0.3,
      size = { 320, 322 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 88",
      name = "potted-plant-88",
      scale = 0.3,
      size = { 320, 356 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 89",
      name = "potted-plant-89",
      scale = 0.3,
      size = { 320, 358 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 90",
      name = "potted-plant-90",
      scale = 0.3,
      size = { 320, 393 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 91",
      name = "potted-plant-91",
      scale = 0.3,
      size = { 320, 317 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 92",
      name = "potted-plant-92",
      scale = 0.3,
      size = { 320, 324 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 93",
      name = "potted-plant-93",
      scale = 0.3,
      size = { 320, 299 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 94",
      name = "potted-plant-94",
      scale = 0.3,
      size = { 320, 405 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 95",
      name = "potted-plant-95",
      scale = 0.3,
      size = { 320, 437 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 96",
      name = "potted-plant-96",
      scale = 0.3,
      size = { 320, 345 },
    },
    {
      ingredients = { { type = "item", name = jellynut, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 97",
      name = "potted-plant-97",
      scale = 0.3,
      size = { 320, 389 },
    },
    {
      ingredients = { { type = "item", name = yumako, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 98",
      name = "potted-plant-98",
      scale = 0.3,
      size = { 320, 442 },
    },
    {
      ingredients = { { type = "item", name = tree, amount = 1 } },
      localised_description = "",
      localised_name = "Plant 99",
      name = "potted-plant-99",
      scale = 0.3,
      size = { 320, 382 },
    },
  },
  animations = {},
})
