local load = require("__mklv-modern-art-lib__.load")

load({
	imagepath = "__mklv-modern-art-potted-plants__/graphics/images/",
	animpath = "__mklv-modern-art-potted-plants__/graphics/animations/",
	images = {
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 0",
			name = "potted-plant-00",
			scale = 1,
			size = { 2266, 3325 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 1",
			name = "potted-plant-01",
			scale = 1,
			size = { 3137, 3784 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 2",
			name = "potted-plant-02",
			scale = 1,
			size = { 2723, 3375 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 3",
			name = "potted-plant-03",
			scale = 1,
			size = { 3144, 3593 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 4",
			name = "potted-plant-04",
			scale = 1,
			size = { 3210, 3720 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 5",
			name = "potted-plant-05",
			scale = 1,
			size = { 2806, 3657 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 6",
			name = "potted-plant-06",
			scale = 1,
			size = { 2753, 3675 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 7",
			name = "potted-plant-07",
			scale = 1,
			size = { 2956, 3833 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 8",
			name = "potted-plant-08",
			scale = 1,
			size = { 2164, 3735 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 9",
			name = "potted-plant-09",
			scale = 1,
			size = { 1912, 3658 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 10",
			name = "potted-plant-10",
			scale = 1,
			size = { 636, 890 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 11",
			name = "potted-plant-11",
			scale = 1,
			size = { 2805, 3395 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 12",
			name = "potted-plant-12",
			scale = 1,
			size = { 3001, 3303 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 13",
			name = "potted-plant-13",
			scale = 1,
			size = { 1993, 3624 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 14",
			name = "potted-plant-14",
			scale = 1,
			size = { 3501, 3586 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 15",
			name = "potted-plant-15",
			scale = 1,
			size = { 2285, 3792 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 16",
			name = "potted-plant-16",
			scale = 1,
			size = { 2890, 3093 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 17",
			name = "potted-plant-17",
			scale = 1,
			size = { 3146, 3401 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 18",
			name = "potted-plant-18",
			scale = 1,
			size = { 2836, 3659 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 19",
			name = "potted-plant-19",
			scale = 1,
			size = { 3003, 3708 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 20",
			name = "potted-plant-20",
			scale = 1,
			size = { 3119, 3100 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 21",
			name = "potted-plant-21",
			scale = 1,
			size = { 3302, 3700 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 22",
			name = "potted-plant-22",
			scale = 1,
			size = { 2955, 3685 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 23",
			name = "potted-plant-23",
			scale = 1,
			size = { 3195, 3735 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 24",
			name = "potted-plant-24",
			scale = 1,
			size = { 3437, 3547 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 25",
			name = "potted-plant-25",
			scale = 1,
			size = { 3117, 3273 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 26",
			name = "potted-plant-26",
			scale = 1,
			size = { 3564, 3826 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 27",
			name = "potted-plant-27",
			scale = 1,
			size = { 3317, 3585 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 28",
			name = "potted-plant-28",
			scale = 1,
			size = { 3252, 3226 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 29",
			name = "potted-plant-29",
			scale = 1,
			size = { 3617, 3794 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 30",
			name = "potted-plant-30",
			scale = 1,
			size = { 2748, 3422 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 31",
			name = "potted-plant-31",
			scale = 1,
			size = { 2879, 3842 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 32",
			name = "potted-plant-32",
			scale = 1,
			size = { 2921, 3681 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 33",
			name = "potted-plant-33",
			scale = 1,
			size = { 3307, 3653 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 34",
			name = "potted-plant-34",
			scale = 1,
			size = { 2678, 3854 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 35",
			name = "potted-plant-35",
			scale = 1,
			size = { 3272, 3549 },
		},
		-- {
		-- 	ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
		-- 	localised_description = "",
		-- 	localised_name = "Plant 36",
		-- 	name = "potted-plant-36",
		-- 	scale = 1,
		-- 	size = { 3455, 5008 },
		-- },
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 37",
			name = "potted-plant-37",
			scale = 1,
			size = { 3213, 3737 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 38",
			name = "potted-plant-38",
			scale = 1,
			size = { 2430, 3475 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 39",
			name = "potted-plant-39",
			scale = 1,
			size = { 3684, 3847 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 40",
			name = "potted-plant-40",
			scale = 1,
			size = { 2992, 3153 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 41",
			name = "potted-plant-41",
			scale = 1,
			size = { 2677, 3565 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 42",
			name = "potted-plant-42",
			scale = 1,
			size = { 2456, 3460 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 43",
			name = "potted-plant-43",
			scale = 1,
			size = { 3512, 3606 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 44",
			name = "potted-plant-44",
			scale = 1,
			size = { 2888, 3283 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 45",
			name = "potted-plant-45",
			scale = 1,
			size = { 3083, 3758 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 46",
			name = "potted-plant-46",
			scale = 1,
			size = { 3247, 3596 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 47",
			name = "potted-plant-47",
			scale = 1,
			size = { 2635, 3266 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 48",
			name = "potted-plant-48",
			scale = 1,
			size = { 3432, 3754 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 49",
			name = "potted-plant-49",
			scale = 1,
			size = { 2539, 3559 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 50",
			name = "potted-plant-50",
			scale = 1,
			size = { 3312, 3705 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 51",
			name = "potted-plant-51",
			scale = 1,
			size = { 3390, 3600 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 52",
			name = "potted-plant-52",
			scale = 1,
			size = { 3091, 3212 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 53",
			name = "potted-plant-53",
			scale = 1,
			size = { 2576, 3616 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 54",
			name = "potted-plant-54",
			scale = 1,
			size = { 3324, 3740 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 55",
			name = "potted-plant-55",
			scale = 1,
			size = { 2726, 3731 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 56",
			name = "potted-plant-56",
			scale = 1,
			size = { 2723, 4061 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 57",
			name = "potted-plant-57",
			scale = 1,
			size = { 2849, 3481 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 58",
			name = "potted-plant-58",
			scale = 1,
			size = { 3167, 3316 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 59",
			name = "potted-plant-59",
			scale = 1,
			size = { 2933, 3808 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 60",
			name = "potted-plant-60",
			scale = 1,
			size = { 2895, 3556 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 61",
			name = "potted-plant-61",
			scale = 1,
			size = { 3528, 3585 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 62",
			name = "potted-plant-62",
			scale = 1,
			size = { 3148, 3764 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 63",
			name = "potted-plant-63",
			scale = 1,
			size = { 3647, 3813 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 64",
			name = "potted-plant-64",
			scale = 1,
			size = { 2577, 3588 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 65",
			name = "potted-plant-65",
			scale = 1,
			size = { 489, 1261 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 66",
			name = "potted-plant-66",
			scale = 1,
			size = { 3263, 3741 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 67",
			name = "potted-plant-67",
			scale = 1,
			size = { 2964, 3364 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 68",
			name = "potted-plant-68",
			scale = 1,
			size = { 2947, 3220 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 69",
			name = "potted-plant-69",
			scale = 1,
			size = { 2967, 3674 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 70",
			name = "potted-plant-70",
			scale = 1,
			size = { 3299, 3580 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 71",
			name = "potted-plant-71",
			scale = 1,
			size = { 2141, 2491 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 72",
			name = "potted-plant-72",
			scale = 1,
			size = { 2935, 3491 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 73",
			name = "potted-plant-73",
			scale = 1,
			size = { 2997, 3772 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 74",
			name = "potted-plant-74",
			scale = 1,
			size = { 2582, 3520 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 75",
			name = "potted-plant-75",
			scale = 1,
			size = { 2654, 3718 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 76",
			name = "potted-plant-76",
			scale = 1,
			size = { 2704, 3463 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 77",
			name = "potted-plant-77",
			scale = 1,
			size = { 2642, 3738 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 78",
			name = "potted-plant-78",
			scale = 1,
			size = { 2639, 3453 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 79",
			name = "potted-plant-79",
			scale = 1,
			size = { 2818, 3596 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 80",
			name = "potted-plant-80",
			scale = 1,
			size = { 2540, 2988 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 81",
			name = "potted-plant-81",
			scale = 1,
			size = { 3253, 3831 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 82",
			name = "potted-plant-82",
			scale = 1,
			size = { 2991, 3472 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 83",
			name = "potted-plant-83",
			scale = 1,
			size = { 2646, 3432 },
		},
		-- {
		-- 	ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
		-- 	localised_description = "",
		-- 	localised_name = "Plant 84",
		-- 	name = "potted-plant-84",
		-- 	scale = 1,
		-- 	size = { 4996, 5116 },
		-- },
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 85",
			name = "potted-plant-85",
			scale = 1,
			size = { 2781, 3438 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 86",
			name = "potted-plant-86",
			scale = 1,
			size = { 2791, 3501 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 87",
			name = "potted-plant-87",
			scale = 1,
			size = { 3845, 3875 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 88",
			name = "potted-plant-88",
			scale = 1,
			size = { 3081, 3428 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 89",
			name = "potted-plant-89",
			scale = 1,
			size = { 3059, 3421 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 90",
			name = "potted-plant-90",
			scale = 1,
			size = { 2748, 3373 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 91",
			name = "potted-plant-91",
			scale = 1,
			size = { 3709, 3670 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 92",
			name = "potted-plant-92",
			scale = 1,
			size = { 3628, 3672 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 93",
			name = "potted-plant-93",
			scale = 1,
			size = { 3742, 3496 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 94",
			name = "potted-plant-94",
			scale = 1,
			size = { 2856, 3618 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 95",
			name = "potted-plant-95",
			scale = 1,
			size = { 2692, 3674 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 96",
			name = "potted-plant-96",
			scale = 1,
			size = { 3474, 3750 },
		},
		{
			ingredients = { { type = "item", name = "jellynut-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 97",
			name = "potted-plant-97",
			scale = 1,
			size = { 2981, 3620 },
		},
		{
			ingredients = { { type = "item", name = "yumako-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 98",
			name = "potted-plant-98",
			scale = 1,
			size = { 2591, 3575 },
		},
		{
			ingredients = { { type = "item", name = "tree-seed", amount = 1 } },
			localised_description = "",
			localised_name = "Plant 99",
			name = "potted-plant-99",
			scale = 1,
			size = { 2805, 3350 },
		},
	},
	animations = {},
})
